'use strict';
const express=require('express'),session=require('express-session'),SQLiteStore=require('connect-sqlite3')(session),bcrypt=require('bcryptjs'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path');
const app=express(),db=new Database(path.join(__dirname,'data','bitacora.sqlite'));const PORT=process.env.PORT||3000;
db.pragma('journal_mode = WAL');db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,profile TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
app.use(express.json({limit:'100kb'}));app.use(session({store:new SQLiteStore({db: 'sessions.sqlite',dir:path.join(__dirname,'data')}),secret:process.env.SESSION_SECRET||'cambiar-por-un-secreto-largo-antes-de-publicar',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*60*60*1000}}));app.use(express.static(path.join(__dirname,'public')));
const ranks=[{min:1,name:'Novato'},{min:5,name:'Aprendiz'},{min:10,name:'Adepto'},{min:15,name:'Veterano'},{min:20,name:'Maestro'},{min:25,name:'Leyenda'}];function levelXP(l){return Math.round(90+(l-1)*35)}function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function id(){return crypto.randomUUID()}function defaults(name,classId){return{name,classId,level:1,xp:0,stats:{cuerpo:0,mente:0,espiritu:0,disciplina:0},streak:0,lastActiveDate:null,quests:[{id:id(),name:'Tomar 2 litros de agua',cat:'cuerpo',xp:10,repeat:'daily',done:false,lastDone:null},{id:id(),name:'Leer 15 minutos',cat:'mente',xp:25,repeat:'daily',done:false,lastDone:null},{id:id(),name:'Meditar 5 minutos',cat:'espiritu',xp:10,repeat:'daily',done:false,lastDone:null},{id:id(),name:'Ordenar el espacio de trabajo',cat:'disciplina',xp:25,repeat:'daily',done:false,lastDone:null}],log:[]}}
function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:'No autenticado'});const row=db.prepare('SELECT profile FROM users WHERE id=?').get(req.session.userId);if(!row){req.session.destroy(()=>{});return res.status(401).json({error:'Sesión inválida'})}req.profile=JSON.parse(row.profile);next()}function save(req){db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(req.profile),req.session.userId)}function reply(res,p){res.json({profile:p})}
app.post('/api/auth/register',async(req,res)=>{try{const {email,password,name,classId}=req.body;if(!email||!/^\S+@\S+\.\S+$/.test(email)||!password||password.length<8||!name?.trim()||name.trim().length>24)return res.status(400).json({error:'Completá nombre, email válido y contraseña de al menos 8 caracteres.'});if(!['guerrero','mago','explorador','druida','alquimista','bardo'].includes(classId))return res.status(400).json({error:'Clase inválida'});const uid=id(),hash=await bcrypt.hash(password,12),profile=defaults(name.trim(),classId);db.prepare('INSERT INTO users(id,email,password_hash,profile) VALUES(?,?,?,?)').run(uid,email.toLowerCase().trim(),hash,JSON.stringify(profile));req.session.userId=uid;reply(res,profile)}catch(e){res.status(e.code==='SQLITE_CONSTRAINT_UNIQUE'?409:500).json({error:e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Ya existe una cuenta con ese email.':'No se pudo crear la cuenta.'})}});
app.post('/api/auth/login',async(req,res)=>{const row=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase().trim());if(!row||!await bcrypt.compare(String(req.body.password||''),row.password_hash))return res.status(401).json({error:'Email o contraseña incorrectos.'});req.session.userId=row.id;reply(res,JSON.parse(row.profile))});app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/profile',auth,(req,res)=>{let changed=false;for(const q of req.profile.quests)if(q.repeat==='daily'&&q.done&&q.lastDone!==today()){q.done=false;changed=true}if(changed)save(req);reply(res,req.profile)});
app.post('/api/profile/reset',auth,(req,res)=>{req.profile=defaults(req.profile.name,req.profile.classId);save(req);reply(res,req.profile)});
app.post('/api/quests',auth,(req,res)=>{const {name,cat,xp,repeat}=req.body;if(typeof name!=='string'||!name.trim()||name.length>60||!['cuerpo','mente','espiritu','disciplina'].includes(cat)||![10,25,50,100].includes(Number(xp))||!['daily','once'].includes(repeat))return res.status(400).json({error:'Datos de misión inválidos'});req.profile.quests.unshift({id:id(),name:name.trim(),cat,xp:Number(xp),repeat,done:false,lastDone:null});save(req);reply(res,req.profile)});
app.delete('/api/quests/:id',auth,(req,res)=>{req.profile.quests=req.profile.quests.filter(q=>q.id!==req.params.id);save(req);reply(res,req.profile)});
app.post('/api/quests/:id/complete',auth,(req,res)=>{const p=req.profile,q=p.quests.find(x=>x.id===req.params.id);if(!q)return res.status(404).json({error:'Misión no encontrada'});if(q.done)return res.status(409).json({error:'La misión ya está completada'});q.done=true;q.lastDone=today();if(p.lastActiveDate!==today()){if(!p.lastActiveDate)p.streak=1;else{const diff=Math.round((new Date(today())-new Date(p.lastActiveDate))/86400000);p.streak=diff===1?p.streak+1:1}p.lastActiveDate=today()}p.stats[q.cat]=(p.stats[q.cat]||0)+1;p.log.unshift({name:q.name,xp:q.xp,cat:q.cat,date:new Date().toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit'})});p.log=p.log.slice(0,20);p.xp+=q.xp;while(p.xp>=levelXP(p.level)){p.xp-=levelXP(p.level);p.level++}save(req);reply(res,p)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Bitácora corriendo en http://localhost:${PORT}`));
